X=MsgBox("SKENOVANY SOUBORU",0+0,"ZA 4 SEKUNDY STISKNETE OK ")

X=MsgBox("V TOMHLE POÈITAÈI BYL NALEZEN VIRUS",0+48,"VAROVANI")

X=MsgBox("CHCETE HO ODSTRANYT",4+48,"VAROVANI")

X=MsgBox("BROBIHA ODSTRANOVANY",1+0,"ZA 4 SEKUNDY STISKNETE OK ")

X=MsgBox("ODSTRANOVANY SE NEPOVEDLO SKUSTE TO ZNOVU",5+48,"VAROVANI")

X=MsgBox("BROBIHA ODSTRANOVANY",1+0,"ZA 4 SEKUNDY STISKNETE OK ")

X=MsgBox("ODSTRANOVANY SE NEPOVEDLO SKUSTE TO ZNOVU",5+48,"VAROVANI")

X=MsgBox("BROBIHA ODSTRANOVANY",1+0,"ZA 4 SEKUNDY STISKNETE OK ")

X=MsgBox("ODSTRANOVANY SE NEPOVEDLO SKUSTE TO ZNOVU",5+48,"VAROVANI")

X=MsgBox("BROBIHA ODSTRANOVANY",1+0,"ZA 4 SEKUNDY STISKNETE OK ")

X=MsgBox("ODSTRANOVANY SE POVEDLO",0+64,"VAROVANI")

X=MsgBox("CHCETE ZRICHLIT POÈITAÈ",4+32,"BOOST")

X=MsgBox("https://www.techspot.com/downloads/downloadnow/7506/?evp=91a508f7a3f5244c06e5b0706bbc39d7&file=10552",4+32,"PØEJDETE NA STRANKU")









